version: "3.7"

services:
  web:
    image: 725311/insta:code
    build: .
    ports:
      - "80:5000"
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name
